#!/usr/bin/env python
import random

rank = random.choice(('A', '2', '3', '4', '5', '6', '7', '8', '9', 'T', 'J', 'Q', 'K'))
suit = random.choice(('clubs', 'diamonds', 'hearts', 'spades'))
x = ()
cards = x in rank != 0 + ' of ' + x in suit != 0


print cards